version: '3.3'

services:  
  db:
    build:
      context: mysql/
      args:
        MYSQL_VERSION: $MYSQL_VERSION
    container_name: mysql_default
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'user123'
      MYSQL_PASSWORD: 'user123'
    volumes:
      - ./config:/etc/mysql/
      - ./data:/var/lib/mysql

