version: '3.3'

services:  
  db:
    image: mysql:5.7
    container_name: mysql_default
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: 'mysql123'
      MYSQL_PASSWORD: 'mysql123'
    volumes:
      - ./config:/etc/mysql/
      - ./data:/var/lib/mysql

